language: php

php:
    - 5.4

before_install:
    - composer install --dev

script:
    - ./vendor/bin/phpcs --standard=tests/phpcs.xml library/
    - ./vendor/bin/phpunit --configuration=tests

notifications:
    email: false
